export const user =  { UPDATE_LOGIN_STATUS:"UPDATE_LOGIN_STATUS"};
export const router = { 
  GET_ROUTER_PARAMS: "GET_ROUTER_PARAMS",
  ADD_ROUTER_ITEM: "ADD_ROUTER_ITEM",
  CLEAN_ROUTER_ARRAY: "CLEAN_ROUTER_ARRAY"
};